name: Test

on:
  push:
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - ubuntu-24.04-arm
          - windows-latest

    steps:
      - uses: actions/checkout@v5
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          bb: latest
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ">=1.24.0"
      - name: Build
        run: "go build -o pod-babashka-go-duckdb main.go"
      - name: Test
        run: "bb test/script.clj"
